version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "Qu1nel"
    labels:
      - "dependencies"
      - "python"
    commit-message:
      prefix: "chore(deps)"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "Qu1nel"
    labels:
      - "dependencies"
      - "ci"
    commit-message:
      prefix: "chore(ci)"
