name: Publish to PyPI

on:
  workflow_dispatch:

jobs:
  publish:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python for publishing
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build dependencies
        run: python -m pip install build

      - name: Build package
        run: make build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
